# Arquivo: grafana/provisioning/ds-prometheus.yaml

apiVersion: 1

datasources:

  - name: Prometheus
    access: proxy
    type: prometheus
    url: http://prometheus:9090

  - name: Grafana
    access: proxy
    type: prometheus
    url: http://grafana:3000  

  - name: RabbitMQ
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    access: proxy
    type: prometheus
    url: http://rabbitmq:15692/

  - name: node_exporter
    access: proxy
    type: prometheus
    url: http://node_exporter:9200


  - name: Ubuntu
    access: proxy
    type: prometheus
    url: http://172.20.15.55:9100
